### PR TITLE
Move HUD disabling and replay creation to DrawableMvisRuleset

### PR DESCRIPTION
**Pull request by Game4all**
# Summary

Follow-up to #6.

- This moves the disabling of the HUD (through the `AllowGameplayOverlays` property) as well as the dummy Replay creation at the `DrawableRuleset` level; thus removing the need for the dummy autoplay mod.

_Please **refrain from merging this for now until the game package version is bumped** (as the code won't compile for now)_

### CODE REVIEW

**Comment by EVAST9919** [comment]
I see you removed autoplay mod. The main reason of having it is to allow alt-tabbing to another window without gameplay being paused. Does it work like this with this pr?

**Comment by Game4all** [comment]
Calling `SetReplay` on DrawableRuleset with a replay will prevent the game from pausing when alt-tabbing (basically what the Autoplay mod does). This PR just moves the replay generation logic as well as the call to `SetReplay` directly into `DrawableMvisRuleset`;

**Comment by Game4all** [comment]
Should be good to go now.

**Comment by EVAST9919** [comment]
Nice, thanks!

**Pull request merged**
